/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPanel;

/**
 *
 * @author Familyytr
 */
public class Client2Frame1 extends javax.swing.JFrame  {
    int balance = 5000;
    public static String res="";
    static DataOutputStream dout;
    static DataInputStream din;
    static Socket s;
    static server ser;
    
 static ServerGui server=new ServerGui();

  
    public Client2Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Withdraw = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        transationBut = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        labal = new javax.swing.JLabel();
        Check = new javax.swing.JButton();
        convert = new javax.swing.JButton();
        client1Rad = new javax.swing.JRadioButton();
        client3Rad = new javax.swing.JRadioButton();
        client2Rad = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client2");

        jPanel1.setBackground(new java.awt.Color(85, 132, 172));

        Withdraw.setBackground(new java.awt.Color(26, 55, 77));
        Withdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Withdraw.setForeground(new java.awt.Color(246, 242, 212));
        Withdraw.setText("Withdraw");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        Deposit.setBackground(new java.awt.Color(26, 55, 77));
        Deposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deposit.setForeground(new java.awt.Color(246, 242, 212));
        Deposit.setText("Deposit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        transationBut.setBackground(new java.awt.Color(26, 55, 77));
        transationBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transationBut.setForeground(new java.awt.Color(246, 242, 212));
        transationBut.setText("transation");
        transationBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transationButActionPerformed(evt);
            }
        });

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("enter amount");

        jButton5.setBackground(new java.awt.Color(26, 55, 77));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(246, 242, 212));
        jButton5.setText("clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        labal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        labal.setForeground(new java.awt.Color(255, 255, 0));

        Check.setBackground(new java.awt.Color(26, 55, 77));
        Check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Check.setForeground(new java.awt.Color(246, 242, 212));
        Check.setText("Balance");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });

        convert.setBackground(new java.awt.Color(26, 55, 77));
        convert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        convert.setForeground(new java.awt.Color(246, 242, 212));
        convert.setText("converter");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        client1Rad.setBackground(new java.awt.Color(85, 132, 172));
        buttonGroup2.add(client1Rad);
        client1Rad.setText("Client1");
        client1Rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client1RadActionPerformed(evt);
            }
        });

        client3Rad.setBackground(new java.awt.Color(85, 132, 172));
        buttonGroup2.add(client3Rad);
        client3Rad.setText("Client3");
        client3Rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client3RadActionPerformed(evt);
            }
        });

        client2Rad.setBackground(new java.awt.Color(85, 132, 172));
        buttonGroup2.add(client2Rad);
        client2Rad.setText("Client2");

        jRadioButton4.setBackground(new java.awt.Color(85, 132, 172));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("EG->US");

        jRadioButton5.setBackground(new java.awt.Color(85, 132, 172));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("US->EG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(transationBut, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton5))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(client1Rad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(client2Rad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(client3Rad)))
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(client1Rad)
                            .addComponent(client3Rad)
                            .addComponent(client2Rad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transationBut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed
//public void actionPerformed(ActionEvent e) {
//Object o=e.getSource();
//  
//  if (o == "withdraw")
//  {
//         res="withdraw";
//  }
//  else if (o == "deposit")
//  {
//         res="deposit";
//  }
//
//    
//
//}


    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
         res="withdraw";
        String mou= t1.getText();
//            try {
//            dout.writeUTF(Withdraw.getText());
//        } catch (IOException ex) {
//            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//        try {
//            dout.writeUTF(t1.getText());
//            
//             } catch (IOException ex) {
//            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            
//                    
        
        
        
        
       int  withdraw =Integer.parseInt(mou);
          if(ser.ClientBalance2 >= withdraw && withdraw<=7000)

        {

           ser.ClientBalance2 = ser.ClientBalance2 - withdraw;
       labal.setText("Please collect your money");
           System.out.println(ser.ClientBalance2);

        }

        else

        {
        labal.setText("Insufficient Balance");
           System.out.println("Insufficient Balance");

         }
     server.setVisible(true);

        server.jTextArea1.append("Mesho withdrawed "+mou+"\n");

          
          
          
    }//GEN-LAST:event_WithdrawActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        
     
     
     
     
     
        String mou= t1.getText();
       int   deposit =Integer.parseInt(mou);
         ser.ClientBalance2 = ser.ClientBalance2 + deposit;
        labal.setText("current blance= "+ser.ClientBalance2);
        System.out.println("Your Money has been successfully depsited");
        
        
           System.out.println(ser.ClientBalance2);

        server.setVisible(true);
        server.jTextArea1.append("Mesho deposited "+mou+"\n");
        
    }//GEN-LAST:event_DepositActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        t1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
    labal.setText("Your Balance is "+Integer.toString(ser.ClientBalance2));
                   String mou= t1.getText();

          server.jTextArea1.append("Mesho Checked balance  "+mou+"\n");


    }//GEN-LAST:event_CheckActionPerformed

    private void transationButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transationButActionPerformed
//       jCheckBox1.setVisible(true);
       client1Rad.setVisible(true);
       client3Rad.setVisible(true);
               String mou= t1.getText();
               int money=Integer.parseInt(mou);
        if (client1Rad.isSelected()) {
            if (ser.ClientBalance2>=money) {
              ser.ClientBalance1+=money;
                ser.ClientBalance2-=money;
                labal.setText("Transation Success");
         server.jTextArea1.append("Mesho Sent money to Bob "+mou+"\n");

            }
             }
             else if (client3Rad.isSelected()) {
            if (ser.ClientBalance2>=money) {
              ser.ClientBalance3+=money;
                ser.ClientBalance2-=money; 
                 labal.setText("Transation Success");
         server.jTextArea1.append("Mesho Sent money to Zizo  "+mou+"\n");

            }
            
       
        }
            else{
                  labal.setText("Your Balance is lower than amount");
  
            }
    
         
            
        

    }//GEN-LAST:event_transationButActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
                jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    
         String mou= t1.getText();
               float money=Float.parseFloat(mou);
               float conv=0,conv2=0;
        if (jRadioButton4.isSelected()) {
           conv=(float) (money/15.5);
          labal.setText(String.valueOf(conv));
                      server.jTextArea1.append("Mesho Converted from EG->US "+mou+"\n");

             }
             else if (jRadioButton5.isSelected()) {
                 conv2=(float) (money*15.5);
          labal.setText(String.valueOf(conv2));
              server.jTextArea1.append("Mesho Converted from EG->EG "+mou+"\n");

             }

            
    }//GEN-LAST:event_convertActionPerformed

    private void client1RadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client1RadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client1RadActionPerformed

    private void client3RadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client3RadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client3RadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client2Frame1().setVisible(true);
                client1Rad.setVisible(false);
                client3Rad.setVisible(false);
                 client2Rad.setVisible(false);
                  jRadioButton4.setVisible(false);
                  jRadioButton5.setVisible(false);
            }
        });
        
        
        
//        s = new Socket("localhost", 8080); //192.168.1.5
//        //create DataOutputStream object to change the output data to form of streams with passing the socket object to
//         dout = new DataOutputStream(s.getOutputStream());
//        
//         din = new DataInputStream(s.getInputStream());
//                 
//        
//    
//          while(true)
//        {
//                 
//         //then a string is used to hold the data entered from the uesr to read it as a line
//          
//            server=new ServerGui();
//            String fromServer="";
//            fromServer=din.readUTF();
//            server.jTextArea1.append(fromServer);
//            System.out.println(fromServer);
//            
//            if("Withdraw".equals(fromServer)){
//              server.jTextArea1.append("Withdrawed"+t1.getText());
//
//            }
//          System.out.println("Server:" + fromServer);
//          //
//          if(t1.getText().equalsIgnoreCase("exist"))
//          {
//              break;
//          }
//        }
//        s.close();
            
            
            
            
            
         
    
    
    
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Check;
    public static javax.swing.JButton Deposit;
    public static javax.swing.JButton Withdraw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JRadioButton client1Rad;
    public static javax.swing.JRadioButton client2Rad;
    public static javax.swing.JRadioButton client3Rad;
    public static javax.swing.JButton convert;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jRadioButton4;
    public static javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JLabel labal;
    public static javax.swing.JTextField t1;
    public static javax.swing.JButton transationBut;
    // End of variables declaration//GEN-END:variables
}
